# version: '3'
services:
  web:
    build:
      context: .
    ports:
      - 8001:80
    volumes:
      - ./app:/code/app:rw

  db:
    container_name: db
    image: mariadb:latest
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "inkomoko"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - "33060:3306"

  adminer:
    image: adminer:latest
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DESIGN: "lucas-sandery"
      ADMINER_DEFAULT_SERVER: "db"
    ports:
      - 9999:8080
